
name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions :
    contents : read
    pages : write
    id-token : write
concurrency:
  group: "pages"
  cancel-in-progress : false
  

jobs:

  deploy:
    environment: 
      name: github-pages
      url: ${{steps.deployment.outputs.pages_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Install the .NET 
    - name: Setup .NET 
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Install Wasm Tools
    - name: Install .NET Wasm Tools
      run: dotnet workload install wasm-tools

    # Restore Dependencias
    - name: Restore Dependencies
      run: dotnet build -C Release --no-restore
    

    # Public .NET
    - name: Public .NET
      run: dotnet publish Mantimentos.csproj.user -C Release -o docs --no-logo
       

    # Upload
    - name: Upload
      uses: actions/upload-pages-artifact@v4


    # Deploy
    - name: Deploy
      id: deployment
      uses: actions/deploy-pages-artifact@v4

  
